version: 0.2

phases: 
  pre_build: 
    commands: 
      - echo logging into Amazon ECR
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w9g7w6e8
  build: 
    commands: 
      - echo Build started 
      - echo Building the Docker image...
      - docker build -t node-app .
      - docker tag node-app:latest public.ecr.aws/w9g7w6e8/node-app:latest
  post_build:
    commands: 
      - echo Build completed
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/w9g7w6e8/node-app:latest
    