version: 0.2

phases: 
  pre_build: 
    commands: 
      - echo logging into Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 102619787958.dkr.ecr.us-east-1.amazonaws.com
   
  build: 
    commands: 
      - echo Build started 
      - echo Building the Docker image...
      - docker build -t node-app:latest .
      - docker tag node-app:latest 102619787958.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
  post_build:
    commands: 
      - echo Build completed
      - echo Pushing the Docker image...
      - docker push 102619787958.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
    
